"""Initial migration.

Revision ID: b1300e121f6a
Revises: 
Create Date: 2023-01-18 18:58:15.067846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1300e121f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('central',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewname', sa.String(), nullable=True),
    sa.Column('review', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('src',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('srcname', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('srcnumb', sa.String(), nullable=True),
    sa.Column('Hoodie', sa.String(), nullable=True),
    sa.Column('sweat', sa.String(), nullable=True),
    sa.Column('bag', sa.String(), nullable=True),
    sa.Column('shirt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tripghana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tripghana')
    op.drop_table('src')
    op.drop_table('review')
    op.drop_table('item')
    op.drop_table('course')
    op.drop_table('central')
    # ### end Alembic commands ###
